server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

spring:
  application:
    name: chat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace